### ISSUE TITLE
validation functions needed

### ISSUE THREAD

**Issue by toschm** [MarkusLange/Arduino-Due-RTC-Library#6]
The SAM supports validating time/date/etc. by register RTC_VER. I assume, that that register reports invalid values when the SAM comes up. It would be very useful for me, to check if its necessary to synchronize the time by NTC.

**Comment by MarkusLange** [comment]
Ok, I implementet the function RTC_clock.get_valid_entry () it returns 0 for valid data. As far as I can tell (Basen on the SAM3X Datasheet Page 258) this returns will link to invalid data:

0b1000 RTC_CALALR has contained invalid data since it was last programmed.
0b0100 RTC_TIMALR has contained invalid data since it was last programmed.
0b0010 RTC_CALR has contained invalid data since it was last programmed.
0b0001 RTC_TIMR has contained invalid data since it was last programmed.

There are also combinations of them. I hope this help, the RTC_VER Register is also checked if you get time or date bye the other functions.

**Comment by toschm** [comment]
Hi Markus,

thank you for the fast reaction, I'll test it and post a feedback in this forum.

Thomas

**Comment by toschm** [comment]
Hi Markus,
finally I was able to check the function, here at my DigiX it always returns 0. After reading a little more, it seems that the validation only checks if the given data is valid.
As the controller comes up with a date 2007-1-1 I check against this.

Thomas
